version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: cafedamanha
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    expose:
    - "5432"